ALTER SESSION SET "_ORACLE_SCRIPT"=true;


CREATE USER APP IDENTIFIED BY app_pass;
GRANT CONNECT, RESOURCE TO APP;
GRANT CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO APP;
ALTER USER APP QUOTA UNLIMITED ON USERS;
